### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by PatrickSkowronek** [utetrapp/geli#785]
This ticket will be a reference to all issues for the next Release 0.8!
There are some small problems we can fix with this issues! Other will be related to this.

- [x] own badges with angular badges
- [ ] Use tree component for download
- [x] Course card should not have a fab button instead only a normal button
- [x] General tab in course edit translation is broken
- [x] Add spacing in download course between card top and text
- [x] Cancel in download course with no selection will through an error
